### ISSUE TITLE
map-app throws FATAL EXCEPTION on Samsung device SCH-I435 running Android version 4.4.2

### ISSUE THREAD

**Issue by zinfin** [Esri/maps-app-android#118]
Application immediately fails on startup with this error:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.esri.android.mapsapp, PID: 26238
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.esri.android.mapsapp/com.esri.android.mapsapp.MapsAppActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class android.support.design.widget.FloatingActionButton
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:146)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.support.design.widget.FloatingActionButton
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                              at com.esri.android.mapsapp.MapFragment.onCreateView(MapFragment.java:248)
                                                                              at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                                              at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                              at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
                                                                              at android.app.Activity.performStart(Activity.java:5460)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:146) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                              at com.esri.android.mapsapp.MapFragment.onCreateView(MapFragment.java:248) 
                                                                              at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                              at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                              at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453) 
                                                                              at android.app.Activity.performStart(Activity.java:5460) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:146) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: android.content.res.Resources$NotFoundException: File res/drawable/fab_ripple.xml from drawable resource ID #0x7f020052
                                                                              at android.content.res.Resources.loadDrawable(Resources.java:3430)
                                                                              at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                              at android.view.View.<init>(View.java:3701)
                                                                              at android.widget.ImageView.<init>(ImageView.java:127)
                                                                              at android.widget.ImageButton.<init>(ImageButton.java:88)
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:108)
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:104)
                                                                              at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                              at com.esri.android.mapsapp.MapFragment.onCreateView(MapFragment.java:248) 
                                                                              at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                              at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                              at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453) 
                                                                              at android.app.Activity.performStart(Activity.java:5460) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:146) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag ripple
                                                                              at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
                                                                              at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
                                                                              at android.content.res.Resources.loadDrawable(Resources.java:3426)
                                                                              at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                              at android.view.View.<init>(View.java:3701) 
                                                                              at android.widget.ImageView.<init>(ImageView.java:127) 
                                                                              at android.widget.ImageButton.<init>(ImageButton.java:88) 
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:108) 
                                                                              at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:104) 
                                                                              at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                              at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                              at com.esri.android.mapsapp.MapFragment.onCreateView(MapFragment.java:248) 
                                                                              at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                              at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                              at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                              at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453) 
                                                                              at android.app.Activity.performStart(Activity.java:5460) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:146) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 

To reproduce, connect Samsung device running Android 4.4.2 (KitKat) and debug application in Android Studio version 1.5.1

**Comment by zinfin** [comment]
This error is being thrown because the floating action button bar references a background [ripple](http://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html) which is only available in API 21 and above.

**Comment by doneill** [comment]
@zinfin thanks makes sense, we just need to remove the reference and it should work then.

**Comment by zinfin** [comment]
The adventure continues...removing the ripple effect from the floating action bar in KitKat results in the floating action bar disappearing from the map(?!).  This seems to be mitigated by adding the MapView to the layout for the fragment instead of dynamically generating and attaching the map in the onCreateView of the MapFragment...onwards.

**Comment by zinfin** [comment]
Merged conflicts from ripple fix.

**Comment by doneill** [comment]
Verified fixed with #125
