### ISSUE TITLE
maps-app FATAL EXCEPTION for Android version 6.0.1 due to SecurityException

### ISSUE THREAD

**Issue by zinfin** [Esri/maps-app-android#122]
Device Nexus 5, Android 6.0.1
On start, the application immediately throws the following exception because as of Android 6, apps needs to explicitly ask for permissions even though the permissions are already in the manifest.  See this [doc](https://developer.android.com/training/permissions/requesting.html).

FATAL EXCEPTION: main
                                                                          Process: com.esri.android.mapsapp, PID: 28375
                                                                          java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
                                                                              at android.os.Parcel.readException(Parcel.java:1620)
                                                                              at android.os.Parcel.readException(Parcel.java:1573)
                                                                              at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:717)
                                                                              at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1200)
                                                                              at com.esri.android.map.LocationDisplayManager$a.a(SourceFile:894)
                                                                              at com.esri.android.map.LocationDisplayManager$a.a(SourceFile:810)
                                                                              at com.esri.android.map.LocationDisplayManager.start(SourceFile:131)
                                                                              at com.esri.android.mapsapp.MapFragment.startLocationTracking(MapFragment.java:1107)
                                                                              at com.esri.android.mapsapp.MapFragment$4.onStatusChanged(MapFragment.java:549)
                                                                              at com.esri.android.map.MapView$1.b(SourceFile:431)
                                                                              at com.esri.android.map.MapView$1.handleMessage(SourceFile:354)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by doneill** [comment]
This is due to an invalid site redirect URI.  To configure a redirect URI

1. Sign into ArcGIS for developers
2. Go to the **Authentication** tab for your maps-app application on ArcGIS for Developers
3. Add a new redirect URI to the list at the bottom of the page.  These redirect URI's represent a valid place that a user can be redirected to after a successful sign on.

You can also configure a [redirect URI on ArcGIS Online](http://doc.arcgis.com/en/arcgis-online/share-maps/add-items.htm#REG_APP) or your own on-premise portal.  You cannot use a redirect URI that begins with `file://`.

**Comment by doneill** [comment]
@zinfin We should better handle the exception when attempting to log in w/o a redirect URI in place.

**Comment by doneill** [comment]
Verified fixed with #126
